# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy React Frontend Docufen App to Prod

env:
  APP_LOCATION: "/dist" # location of your client code
  APP_ARTIFACT_LOCATION: "/" # location of client code build output

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  build:
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    # if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    name: Build and Test
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install
        run: npm ci
      - uses: oke-py/npm-audit-action@v2.4.4
        with:
          audit_level: low
          production_flag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
      - name: Build
        env:
          VITE_AMPLITUDE_API_KEY_PROD: ${{ secrets.VITE_AMPLITUDE_API_KEY_PROD }}
          VITE_DOCUMENT_UTILS_URL: "editor.docufen.com"
        run: npm run build
      - name: Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.PROD_STATIC_WEBAPP_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}

